create table car (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	make VARCHAR(100) NOT NULL,
	model VARCHAR(100) NOT NULL,
	price MONEY NOT NULL
);

INSERT INTO Car (make, model, price) VALUES ('Scion', 'tC', '$88314.40');
INSERT INTO Car (make, model, price) VALUES ('Mercury', 'Cougar', '$89777.19');
INSERT INTO Car (make, model, price) VALUES ('Oldsmobile', 'Cutlass Cruiser', '$94242.77');
INSERT INTO Car (make, model, price) VALUES ('Hyundai', 'Veracruz', '$57429.78');
INSERT INTO Car (make, model, price) VALUES ('Suzuki', 'SJ', '$11445.73');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', '400E', '$75533.31');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Scirocco', '$54121.57');
INSERT INTO Car (make, model, price) VALUES ('Cadillac', 'DeVille', '$21590.97');
INSERT INTO Car (make, model, price) VALUES ('Acura', 'Vigor', '$53111.17');
INSERT INTO Car (make, model, price) VALUES ('Oldsmobile', 'LSS', '$12287.11');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Safari', '$36378.42');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'CL-Class', '$53952.41');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'Familia', '$79278.23');
INSERT INTO Car (make, model, price) VALUES ('Bentley', 'Continental', '$44840.98');
INSERT INTO Car (make, model, price) VALUES ('Subaru', 'Forester', '$86412.77');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'F350', '$32971.92');
INSERT INTO Car (make, model, price) VALUES ('Aston Martin', 'V12 Vantage', '$69158.24');
INSERT INTO Car (make, model, price) VALUES ('Chrysler', 'Sebring', '$50009.21');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Mirage', '$34489.76');
INSERT INTO Car (make, model, price) VALUES ('Land Rover', 'Defender', '$29205.92');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Tacoma', '$12133.87');
INSERT INTO Car (make, model, price) VALUES ('Buick', 'Skylark', '$31959.62');
INSERT INTO Car (make, model, price) VALUES ('Suzuki', 'Swift', '$76252.97');
INSERT INTO Car (make, model, price) VALUES ('Volvo', 'S80', '$98840.03');
INSERT INTO Car (make, model, price) VALUES ('Studebaker', 'Avanti', '$18876.48');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Caravan', '$90828.50');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Endeavor', '$59371.09');
INSERT INTO Car (make, model, price) VALUES ('Jeep', 'Commander', '$93537.88');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Lancer', '$24548.01');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Camaro', '$87773.61');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Camaro', '$92598.01');
INSERT INTO Car (make, model, price) VALUES ('Cadillac', 'Escalade EXT', '$26450.55');
INSERT INTO Car (make, model, price) VALUES ('Jeep', 'Patriot', '$70205.81');
INSERT INTO Car (make, model, price) VALUES ('Chrysler', 'Voyager', '$66568.49');
INSERT INTO Car (make, model, price) VALUES ('BMW', 'Z4', '$42319.97');
INSERT INTO Car (make, model, price) VALUES ('Land Rover', 'Defender 90', '$91316.17');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Ranger', '$46703.27');
INSERT INTO Car (make, model, price) VALUES ('Lotus', 'Esprit', '$68381.02');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Ram 2500', '$54504.75');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Jetta', '$87343.74');
INSERT INTO Car (make, model, price) VALUES ('Kia', 'Sorento', '$59958.86');
INSERT INTO Car (make, model, price) VALUES ('Suzuki', 'Esteem', '$98801.06');
INSERT INTO Car (make, model, price) VALUES ('MINI', 'MINI', '$41981.46');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'GLK-Class', '$12258.19');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Jetta', '$51589.62');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Thunderbird', '$66826.76');
INSERT INTO Car (make, model, price) VALUES ('Plymouth', 'Voyager', '$25537.40');
INSERT INTO Car (make, model, price) VALUES ('Lexus', 'IS', '$46336.79');
INSERT INTO Car (make, model, price) VALUES ('Suzuki', 'Daewoo Lacetti', '$78704.59');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Jetta', '$54703.84');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'S10', '$11228.35');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Touareg', '$45031.34');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Grand Caravan', '$53932.12');
INSERT INTO Car (make, model, price) VALUES ('BMW', '6 Series', '$74651.53');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'G-Class', '$71624.04');
INSERT INTO Car (make, model, price) VALUES ('MINI', 'Countryman', '$30622.08');
INSERT INTO Car (make, model, price) VALUES ('Suzuki', 'Forenza', '$58485.08');
INSERT INTO Car (make, model, price) VALUES ('Buick', 'Somerset', '$42708.31');
INSERT INTO Car (make, model, price) VALUES ('Mercury', 'Capri', '$45170.73');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Charger', '$20650.23');
INSERT INTO Car (make, model, price) VALUES ('Buick', 'Park Avenue', '$36277.45');
INSERT INTO Car (make, model, price) VALUES ('Mercury', 'Milan', '$38869.28');
INSERT INTO Car (make, model, price) VALUES ('Volvo', 'XC90', '$49077.68');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'T100', '$69596.83');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Ram 1500', '$98880.27');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'Mazda6', '$48052.10');
INSERT INTO Car (make, model, price) VALUES ('MINI', 'Clubman', '$70875.89');
INSERT INTO Car (make, model, price) VALUES ('Volvo', 'S80', '$46582.75');
INSERT INTO Car (make, model, price) VALUES ('Buick', 'Somerset', '$71024.21');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Outlander', '$94897.09');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'MPV', '$87366.44');
INSERT INTO Car (make, model, price) VALUES ('Land Rover', 'Range Rover', '$53678.64');
INSERT INTO Car (make, model, price) VALUES ('Land Rover', 'Freelander', '$65595.04');
INSERT INTO Car (make, model, price) VALUES ('Plymouth', 'Grand Voyager', '$40888.47');
INSERT INTO Car (make, model, price) VALUES ('BMW', 'X5', '$95014.39');
INSERT INTO Car (make, model, price) VALUES ('Saab', '9-5', '$83385.20');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Golf', '$54049.19');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Viper', '$49561.68');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'F450', '$65809.67');
INSERT INTO Car (make, model, price) VALUES ('Chrysler', 'LeBaron', '$92554.30');
INSERT INTO Car (make, model, price) VALUES ('Oldsmobile', 'Silhouette', '$65890.56');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Silverado', '$67076.85');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'S-Class', '$69902.81');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Stealth', '$18697.68');
INSERT INTO Car (make, model, price) VALUES ('Acura', 'TL', '$78044.20');
INSERT INTO Car (make, model, price) VALUES ('Land Rover', 'LR2', '$95619.72');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Suburban 1500', '$48707.92');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Blazer', '$99724.50');
INSERT INTO Car (make, model, price) VALUES ('Aston Martin', 'DBS', '$46157.97');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Sierra 2500', '$48843.87');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Explorer Sport Trac', '$27115.08');
INSERT INTO Car (make, model, price) VALUES ('Hyundai', 'Elantra', '$38602.36');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Mustang', '$43635.68');
INSERT INTO Car (make, model, price) VALUES ('Nissan', 'Altima', '$22925.45');
INSERT INTO Car (make, model, price) VALUES ('Honda', 'Fit', '$83104.47');
INSERT INTO Car (make, model, price) VALUES ('Suzuki', 'Forenza', '$23580.79');
INSERT INTO Car (make, model, price) VALUES ('Subaru', 'Outback', '$99910.72');
INSERT INTO Car (make, model, price) VALUES ('BMW', '600', '$68358.97');
INSERT INTO Car (make, model, price) VALUES ('Volvo', 'S80', '$63028.69');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Corvette', '$67569.74');
INSERT INTO Car (make, model, price) VALUES ('BMW', '8 Series', '$50250.96');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'F-Series', '$96054.75');
INSERT INTO Car (make, model, price) VALUES ('Subaru', 'Justy', '$20122.57');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Avalanche 1500', '$59884.60');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Camaro', '$12115.80');
INSERT INTO Car (make, model, price) VALUES ('Porsche', '928', '$41152.96');
INSERT INTO Car (make, model, price) VALUES ('Oldsmobile', '98', '$81716.61');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'G55 AMG', '$48436.56');
INSERT INTO Car (make, model, price) VALUES ('Morgan', 'Aero 8', '$37163.27');
INSERT INTO Car (make, model, price) VALUES ('Lincoln', 'MKX', '$24391.37');
INSERT INTO Car (make, model, price) VALUES ('Mazda', '929', '$65894.36');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Mighty Max', '$94938.85');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Parisienne', '$82806.75');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'F-Series', '$74180.19');
INSERT INTO Car (make, model, price) VALUES ('Oldsmobile', 'Bravada', '$39628.85');
INSERT INTO Car (make, model, price) VALUES ('Nissan', 'Quest', '$67248.32');
INSERT INTO Car (make, model, price) VALUES ('Cadillac', 'Eldorado', '$73151.49');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Ram 2500', '$39544.85');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Corrado', '$74260.34');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'Mazda3', '$32598.40');
INSERT INTO Car (make, model, price) VALUES ('Lincoln', 'LS', '$58911.16');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Ram', '$84088.61');
INSERT INTO Car (make, model, price) VALUES ('Nissan', 'Titan', '$28673.02');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Ranger', '$10825.28');
INSERT INTO Car (make, model, price) VALUES ('Infiniti', 'QX', '$81162.64');
INSERT INTO Car (make, model, price) VALUES ('Kia', 'Forte', '$32836.81');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Echo', '$56899.63');
INSERT INTO Car (make, model, price) VALUES ('Scion', 'tC', '$92652.87');
INSERT INTO Car (make, model, price) VALUES ('Lexus', 'LX', '$12686.56');
INSERT INTO Car (make, model, price) VALUES ('Oldsmobile', 'Bravada', '$44447.94');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'F150', '$25767.38');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'E-Class', '$42667.29');
INSERT INTO Car (make, model, price) VALUES ('Audi', 'S4', '$62394.98');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Viper', '$69513.89');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'Mazda6', '$13166.95');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'S-Class', '$30704.34');
INSERT INTO Car (make, model, price) VALUES ('Cadillac', 'SRX', '$18317.35');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Galant', '$11460.39');
INSERT INTO Car (make, model, price) VALUES ('Plymouth', 'Prowler', '$80819.28');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Passat', '$43620.28');
INSERT INTO Car (make, model, price) VALUES ('Saturn', 'S-Series', '$87407.54');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Sonoma', '$27935.25');
INSERT INTO Car (make, model, price) VALUES ('Audi', 'S8', '$43778.91');
INSERT INTO Car (make, model, price) VALUES ('Chrysler', 'Cirrus', '$79418.09');
INSERT INTO Car (make, model, price) VALUES ('Bentley', 'Continental Flying Spur', '$38124.81');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'F450', '$65654.67');
INSERT INTO Car (make, model, price) VALUES ('Subaru', 'Legacy', '$83535.66');
INSERT INTO Car (make, model, price) VALUES ('Hyundai', 'Scoupe', '$58112.52');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Taurus', '$27377.18');
INSERT INTO Car (make, model, price) VALUES ('Infiniti', 'QX56', '$38807.49');
INSERT INTO Car (make, model, price) VALUES ('Lotus', 'Esprit', '$21673.44');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Touareg', '$76514.54');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Bonneville', '$84647.24');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'Mazda6', '$84802.05');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Savana', '$26211.71');
INSERT INTO Car (make, model, price) VALUES ('Cadillac', 'Escalade ESV', '$57877.47');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Mustang', '$18168.87');
INSERT INTO Car (make, model, price) VALUES ('Cadillac', 'Allante', '$69102.20');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Rally Wagon 1500', '$24492.83');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Grand Prix', '$52677.31');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Xtra', '$59392.82');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'RX-8', '$11634.14');
INSERT INTO Car (make, model, price) VALUES ('Subaru', 'Forester', '$15860.61');
INSERT INTO Car (make, model, price) VALUES ('MINI', 'Cooper Clubman', '$66693.90');
INSERT INTO Car (make, model, price) VALUES ('Saturn', 'Outlook', '$31366.11');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'New Beetle', '$26791.87');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'MPV', '$18748.64');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'GTI', '$46229.14');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'ZX2', '$16136.67');
INSERT INTO Car (make, model, price) VALUES ('Nissan', 'Titan', '$96423.22');
INSERT INTO Car (make, model, price) VALUES ('Mercury', 'Cougar', '$82578.92');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Fox', '$27685.38');
INSERT INTO Car (make, model, price) VALUES ('GMC', '2500', '$92631.52');
INSERT INTO Car (make, model, price) VALUES ('Mercury', 'Mystique', '$25198.45');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Tempo', '$55747.56');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Sonoma', '$35378.40');
INSERT INTO Car (make, model, price) VALUES ('Cadillac', 'SRX', '$99290.64');
INSERT INTO Car (make, model, price) VALUES ('Maybach', '57', '$89021.86');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Firefly', '$25215.99');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Mirage', '$93078.40');
INSERT INTO Car (make, model, price) VALUES ('Mazda', '929', '$66157.38');
INSERT INTO Car (make, model, price) VALUES ('Porsche', '968', '$84592.36');
INSERT INTO Car (make, model, price) VALUES ('Buick', 'Park Avenue', '$96637.84');
INSERT INTO Car (make, model, price) VALUES ('BMW', '1 Series', '$63590.94');
INSERT INTO Car (make, model, price) VALUES ('Suzuki', 'Aerio', '$18487.97');
INSERT INTO Car (make, model, price) VALUES ('Mercury', 'Sable', '$76865.71');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'S10', '$42047.17');
INSERT INTO Car (make, model, price) VALUES ('Buick', 'Regal', '$63988.99');
INSERT INTO Car (make, model, price) VALUES ('Buick', 'Lucerne', '$32560.37');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Land Cruiser', '$93137.36');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Ram Van 2500', '$81477.40');
INSERT INTO Car (make, model, price) VALUES ('Chrysler', 'PT Cruiser', '$62213.07');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'SLK-Class', '$53608.51');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'R-Class', '$47344.84');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Corvette', '$90615.68');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Safari', '$97247.47');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Jimmy', '$47606.95');
INSERT INTO Car (make, model, price) VALUES ('Audi', 'A8', '$80991.73');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Sportvan G30', '$22365.58');
INSERT INTO Car (make, model, price) VALUES ('Plymouth', 'Breeze', '$97877.90');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Suburban 2500', '$85560.49');
INSERT INTO Car (make, model, price) VALUES ('Isuzu', 'i-370', '$74766.11');
INSERT INTO Car (make, model, price) VALUES ('BMW', 'X3', '$14938.87');
INSERT INTO Car (make, model, price) VALUES ('BMW', '5 Series', '$22789.64');
INSERT INTO Car (make, model, price) VALUES ('Saturn', 'VUE', '$30970.15');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Dakota', '$19465.76');
INSERT INTO Car (make, model, price) VALUES ('Saab', '900', '$34813.82');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Corvette', '$11364.28');
INSERT INTO Car (make, model, price) VALUES ('Honda', 'Civic', '$36783.31');
INSERT INTO Car (make, model, price) VALUES ('Mercury', 'Mariner', '$29268.90');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'F350', '$89967.58');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Sierra 3500', '$21846.20');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Express', '$53073.24');
INSERT INTO Car (make, model, price) VALUES ('Mercury', 'Mountaineer', '$57456.32');
INSERT INTO Car (make, model, price) VALUES ('Infiniti', 'I', '$89825.82');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Safari', '$27376.40');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Astro', '$68457.28');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Silverado 2500', '$69303.69');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Grand Caravan', '$71379.79');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Tahoe', '$81180.49');
INSERT INTO Car (make, model, price) VALUES ('Oldsmobile', 'Silhouette', '$76824.88');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'G-Class', '$15562.43');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'LTD Crown Victoria', '$79466.78');
INSERT INTO Car (make, model, price) VALUES ('Chrysler', '300M', '$43150.02');
INSERT INTO Car (make, model, price) VALUES ('Lamborghini', 'Murciélago', '$31278.36');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Golf', '$29566.47');
INSERT INTO Car (make, model, price) VALUES ('Suzuki', 'SJ', '$83763.58');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Expedition EL', '$99449.49');
INSERT INTO Car (make, model, price) VALUES ('Kia', 'Rio', '$72531.85');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'CL-Class', '$49676.02');
INSERT INTO Car (make, model, price) VALUES ('Porsche', 'Boxster', '$43134.14');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Contour', '$76180.37');
INSERT INTO Car (make, model, price) VALUES ('Shelby', 'GT500', '$58968.92');
INSERT INTO Car (make, model, price) VALUES ('Lincoln', 'Navigator', '$99627.76');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'SLK-Class', '$85071.23');
INSERT INTO Car (make, model, price) VALUES ('Lexus', 'SC', '$40149.84');
INSERT INTO Car (make, model, price) VALUES ('Chrysler', 'Town & Country', '$63589.48');
INSERT INTO Car (make, model, price) VALUES ('Mercury', 'Topaz', '$80953.71');
INSERT INTO Car (make, model, price) VALUES ('Lotus', 'Elan', '$92434.87');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Thunderbird', '$19690.63');
INSERT INTO Car (make, model, price) VALUES ('Suzuki', 'Swift', '$23157.89');
INSERT INTO Car (make, model, price) VALUES ('Hyundai', 'Equus', '$78682.23');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Escape', '$76982.96');
INSERT INTO Car (make, model, price) VALUES ('Cadillac', 'SRX', '$13926.54');
INSERT INTO Car (make, model, price) VALUES ('Kia', 'Optima', '$70272.75');
INSERT INTO Car (make, model, price) VALUES ('Mercury', 'Cougar', '$76293.89');
INSERT INTO Car (make, model, price) VALUES ('Acura', 'NSX', '$47729.68');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'S10', '$10123.40');
INSERT INTO Car (make, model, price) VALUES ('Mercury', 'Mystique', '$76334.15');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Routan', '$68889.77');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Thunderbird', '$52139.91');
INSERT INTO Car (make, model, price) VALUES ('Nissan', 'Rogue', '$72771.71');
INSERT INTO Car (make, model, price) VALUES ('Daihatsu', 'Rocky', '$78267.91');
INSERT INTO Car (make, model, price) VALUES ('Lexus', 'RX', '$52781.33');
INSERT INTO Car (make, model, price) VALUES ('BMW', 'M Roadster', '$87007.66');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Tacoma', '$70463.37');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Pajero', '$86873.94');
INSERT INTO Car (make, model, price) VALUES ('Lexus', 'SC', '$34030.43');
INSERT INTO Car (make, model, price) VALUES ('Buick', 'Roadmaster', '$39767.49');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Montana SV6', '$96615.93');
INSERT INTO Car (make, model, price) VALUES ('Chrysler', 'LHS', '$54369.14');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Sunbird', '$96329.55');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Solara', '$10646.31');
INSERT INTO Car (make, model, price) VALUES ('Cadillac', 'XLR', '$64477.23');
INSERT INTO Car (make, model, price) VALUES ('Nissan', 'Sentra', '$75986.25');
INSERT INTO Car (make, model, price) VALUES ('Lotus', 'Esprit', '$51283.25');
INSERT INTO Car (make, model, price) VALUES ('Lotus', 'Evora', '$76955.82');
INSERT INTO Car (make, model, price) VALUES ('Lexus', 'LS Hybrid', '$23078.83');
INSERT INTO Car (make, model, price) VALUES ('Chrysler', 'Crossfire', '$15162.56');
INSERT INTO Car (make, model, price) VALUES ('Acura', 'RL', '$76902.97');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Express 3500', '$86297.27');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', '300CE', '$17552.52');
INSERT INTO Car (make, model, price) VALUES ('Scion', 'xB', '$88898.63');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Ram 1500', '$18627.01');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Stratus', '$17720.56');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Taurus X', '$64007.24');
INSERT INTO Car (make, model, price) VALUES ('Toyota', '4Runner', '$83279.98');
INSERT INTO Car (make, model, price) VALUES ('Saturn', 'L-Series', '$26638.46');
INSERT INTO Car (make, model, price) VALUES ('Cadillac', 'CTS', '$85175.81');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', '500E', '$16419.43');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Dakota', '$75741.54');
INSERT INTO Car (make, model, price) VALUES ('Plymouth', 'Voyager', '$32815.39');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'G-Series 2500', '$26125.21');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'RAV4', '$94584.26');
INSERT INTO Car (make, model, price) VALUES ('Fillmore', 'Fillmore', '$28439.07');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'Sprinter', '$31928.44');
INSERT INTO Car (make, model, price) VALUES ('Lotus', 'Esprit', '$33476.43');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Aerostar', '$80295.08');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Bonneville', '$46782.54');
INSERT INTO Car (make, model, price) VALUES ('Audi', 'riolet', '$10338.23');
INSERT INTO Car (make, model, price) VALUES ('Acura', 'RL', '$93796.32');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Colorado', '$75039.98');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Ram 2500', '$58623.06');
INSERT INTO Car (make, model, price) VALUES ('Nissan', '240SX', '$97563.10');
INSERT INTO Car (make, model, price) VALUES ('Mercury', 'Cougar', '$19371.85');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Tempo', '$59259.53');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'C-Class', '$31518.86');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Firebird', '$26976.46');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Astro', '$46773.94');
INSERT INTO Car (make, model, price) VALUES ('Saturn', 'Aura', '$61187.77');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Shadow', '$98097.02');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Tundra', '$33923.63');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Corvette', '$58499.12');
INSERT INTO Car (make, model, price) VALUES ('Honda', 'Accord', '$18990.35');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'E150', '$89835.99');
INSERT INTO Car (make, model, price) VALUES ('BMW', '7 Series', '$80094.64');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Yaris', '$70862.56');
INSERT INTO Car (make, model, price) VALUES ('Acura', 'RL', '$59890.21');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Starion', '$36130.58');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Sonoma Club', '$23275.90');
INSERT INTO Car (make, model, price) VALUES ('Lexus', 'IS', '$32376.66');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Eurovan', '$58252.50');
INSERT INTO Car (make, model, price) VALUES ('Lamborghini', 'Gallardo', '$47160.37');
INSERT INTO Car (make, model, price) VALUES ('Buick', 'Century', '$36958.68');
INSERT INTO Car (make, model, price) VALUES ('Buick', 'Regal', '$91114.38');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', '300TE', '$55236.95');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Tundra', '$66595.21');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Silverado 1500', '$86647.85');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Eclipse', '$67855.28');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Explorer Sport Trac', '$58973.85');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'F250', '$80581.68');
INSERT INTO Car (make, model, price) VALUES ('Chrysler', 'New Yorker', '$66789.95');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'S-Class', '$35901.38');
INSERT INTO Car (make, model, price) VALUES ('Land Rover', 'Range Rover', '$19291.91');
INSERT INTO Car (make, model, price) VALUES ('Nissan', 'Pathfinder', '$31402.33');
INSERT INTO Car (make, model, price) VALUES ('Jaguar', 'X-Type', '$15219.76');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Club Wagon', '$17580.49');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'SL-Class', '$27556.36');
INSERT INTO Car (make, model, price) VALUES ('Daewoo', 'Leganza', '$83675.36');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'Familia', '$96822.43');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'Mazda6', '$44444.15');
INSERT INTO Car (make, model, price) VALUES ('Porsche', '968', '$79060.04');
INSERT INTO Car (make, model, price) VALUES ('Lexus', 'SC', '$12541.76');
INSERT INTO Car (make, model, price) VALUES ('Lexus', 'ES', '$39359.06');
INSERT INTO Car (make, model, price) VALUES ('Buick', 'Riviera', '$43583.82');
INSERT INTO Car (make, model, price) VALUES ('GMC', '3500 Club Coupe', '$32256.95');
INSERT INTO Car (make, model, price) VALUES ('Infiniti', 'I', '$84051.37');
INSERT INTO Car (make, model, price) VALUES ('Mercury', 'Grand Marquis', '$23605.90');
INSERT INTO Car (make, model, price) VALUES ('Volvo', 'S40', '$69078.83');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Camry', '$84807.41');
INSERT INTO Car (make, model, price) VALUES ('Volvo', '850', '$44655.66');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Golf', '$25998.38');
INSERT INTO Car (make, model, price) VALUES ('Land Rover', 'Defender', '$35911.84');
INSERT INTO Car (make, model, price) VALUES ('Infiniti', 'Q', '$27335.41');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Jimmy', '$15211.95');
INSERT INTO Car (make, model, price) VALUES ('Cadillac', 'Escalade EXT', '$74364.13');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Avalon', '$33195.33');
INSERT INTO Car (make, model, price) VALUES ('Saturn', 'S-Series', '$96690.92');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Galant', '$62676.09');
INSERT INTO Car (make, model, price) VALUES ('Audi', 'A7', '$55002.99');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Camaro', '$68858.92');
INSERT INTO Car (make, model, price) VALUES ('Saab', '9-7X', '$39029.90');
INSERT INTO Car (make, model, price) VALUES ('Suzuki', 'Forenza', '$62517.66');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'B-Series', '$53870.31');
INSERT INTO Car (make, model, price) VALUES ('Suzuki', 'Swift', '$54360.89');
INSERT INTO Car (make, model, price) VALUES ('Infiniti', 'Q', '$66245.19');
INSERT INTO Car (make, model, price) VALUES ('Kia', 'Sephia', '$52603.51');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'Mazdaspeed 3', '$48861.09');
INSERT INTO Car (make, model, price) VALUES ('MINI', 'Countryman', '$26753.59');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Escort', '$51191.43');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Rally Wagon 3500', '$55500.09');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Tacoma Xtra', '$71892.04');
INSERT INTO Car (make, model, price) VALUES ('Jeep', 'Wrangler', '$89945.92');
INSERT INTO Car (make, model, price) VALUES ('Porsche', '911', '$84327.61');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'F250', '$23982.08');
INSERT INTO Car (make, model, price) VALUES ('BMW', 'X3', '$32358.88');
INSERT INTO Car (make, model, price) VALUES ('Porsche', '911', '$82503.31');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'SLR McLaren', '$52156.03');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', '2500', '$51422.48');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Savana', '$64091.28');
INSERT INTO Car (make, model, price) VALUES ('Plymouth', 'Breeze', '$62750.92');
INSERT INTO Car (make, model, price) VALUES ('Plymouth', 'Sundance', '$64749.87');
INSERT INTO Car (make, model, price) VALUES ('Mercury', 'Grand Marquis', '$69840.38');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'G6', '$37004.48');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Equinox', '$96543.84');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Savana 1500', '$99441.58');
INSERT INTO Car (make, model, price) VALUES ('BMW', '3 Series', '$96911.32');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Corolla', '$88299.12');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'GTI', '$89910.39');
INSERT INTO Car (make, model, price) VALUES ('Mercury', 'Cougar', '$18375.53');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Tempo', '$24121.53');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Suburban 1500', '$43581.46');
INSERT INTO Car (make, model, price) VALUES ('Toyota', '4Runner', '$30901.85');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Grand Prix', '$62212.27');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Escort', '$66368.40');
INSERT INTO Car (make, model, price) VALUES ('Land Rover', 'Sterling', '$59868.59');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Silverado', '$66465.18');
INSERT INTO Car (make, model, price) VALUES ('Audi', 'Coupe GT', '$84916.41');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Firefly', '$28224.34');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Highlander', '$11923.66');
INSERT INTO Car (make, model, price) VALUES ('Lincoln', 'Continental Mark VII', '$25648.91');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Sienna', '$65179.56');
INSERT INTO Car (make, model, price) VALUES ('Cadillac', 'Eldorado', '$33791.00');
INSERT INTO Car (make, model, price) VALUES ('Nissan', 'Sentra', '$83734.99');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'CL-Class', '$77711.44');
INSERT INTO Car (make, model, price) VALUES ('Mercury', 'Grand Marquis', '$68536.15');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', '500SEC', '$12435.37');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'S10', '$17923.95');
INSERT INTO Car (make, model, price) VALUES ('Lexus', 'IS', '$45939.44');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', '190E', '$73037.27');
INSERT INTO Car (make, model, price) VALUES ('Saab', '9-7X', '$86765.50');
INSERT INTO Car (make, model, price) VALUES ('Tesla', 'Roadster', '$86758.94');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Land Cruiser', '$87910.37');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Corvette', '$67620.62');
INSERT INTO Car (make, model, price) VALUES ('Oldsmobile', 'Bravada', '$46482.91');
INSERT INTO Car (make, model, price) VALUES ('Mazda', '929', '$17084.64');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'MPV', '$89462.47');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Probe', '$62172.08');
INSERT INTO Car (make, model, price) VALUES ('Nissan', 'Sentra', '$98637.49');
INSERT INTO Car (make, model, price) VALUES ('Saab', '9-3', '$28999.71');
INSERT INTO Car (make, model, price) VALUES ('Buick', 'Regal', '$86537.18');
INSERT INTO Car (make, model, price) VALUES ('Lincoln', 'Mark LT', '$20924.22');
INSERT INTO Car (make, model, price) VALUES ('Lexus', 'RX Hybrid', '$85865.11');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Thunderbird', '$75681.23');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Yukon XL 2500', '$13468.51');
INSERT INTO Car (make, model, price) VALUES ('Volvo', 'V50', '$33507.83');
INSERT INTO Car (make, model, price) VALUES ('Lincoln', 'Navigator L', '$33953.41');
INSERT INTO Car (make, model, price) VALUES ('Aston Martin', 'V8 Vantage', '$93148.98');
INSERT INTO Car (make, model, price) VALUES ('Buick', 'Enclave', '$72309.49');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'G-Class', '$99589.03');
INSERT INTO Car (make, model, price) VALUES ('Mercury', 'Grand Marquis', '$78895.58');
INSERT INTO Car (make, model, price) VALUES ('Infiniti', 'Q', '$35393.24');
INSERT INTO Car (make, model, price) VALUES ('Infiniti', 'G37', '$93804.57');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Diamante', '$32525.51');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'TrailBlazer', '$15902.14');
INSERT INTO Car (make, model, price) VALUES ('Volvo', 'S60', '$88519.80');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Tahoe', '$26631.16');
INSERT INTO Car (make, model, price) VALUES ('Chrysler', 'Sebring', '$67604.39');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'TrailBlazer', '$77036.57');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Explorer', '$15223.19');
INSERT INTO Car (make, model, price) VALUES ('BMW', '760', '$81804.76');
INSERT INTO Car (make, model, price) VALUES ('BMW', 'X5', '$84892.83');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Cavalier', '$10890.76');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Corvette', '$75427.08');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'CLK-Class', '$62635.90');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'E-Class', '$51536.60');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Sequoia', '$58483.78');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'RAV4', '$56290.86');
INSERT INTO Car (make, model, price) VALUES ('Lexus', 'GX', '$83887.27');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'SL-Class', '$42041.64');
INSERT INTO Car (make, model, price) VALUES ('Honda', 'S2000', '$67088.20');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'E-Series', '$51317.73');
INSERT INTO Car (make, model, price) VALUES ('Cadillac', 'Escalade EXT', '$22139.78');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'B-Series', '$33530.90');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Aveo', '$23324.86');
INSERT INTO Car (make, model, price) VALUES ('BMW', '525', '$99646.03');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Astro', '$36974.58');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Mighty Max', '$47502.16');
INSERT INTO Car (make, model, price) VALUES ('Maserati', '430', '$24244.55');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Lancer', '$67449.34');
INSERT INTO Car (make, model, price) VALUES ('Honda', 'CR-V', '$67504.56');
INSERT INTO Car (make, model, price) VALUES ('Lincoln', 'Town Car', '$91107.37');
INSERT INTO Car (make, model, price) VALUES ('Lexus', 'ES', '$66615.70');
INSERT INTO Car (make, model, price) VALUES ('Cadillac', 'Sixty Special', '$27033.94');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Windstar', '$15775.83');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Viper', '$57814.19');
INSERT INTO Car (make, model, price) VALUES ('Aston Martin', 'DB9', '$60931.12');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'F250', '$87471.26');
INSERT INTO Car (make, model, price) VALUES ('Hyundai', 'Entourage', '$59815.28');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'Miata MX-5', '$14579.15');
INSERT INTO Car (make, model, price) VALUES ('Bentley', 'Continental GTC', '$95813.22');
INSERT INTO Car (make, model, price) VALUES ('Audi', 'S4', '$49472.40');
INSERT INTO Car (make, model, price) VALUES ('Subaru', 'Leone', '$95673.09');
INSERT INTO Car (make, model, price) VALUES ('Lincoln', 'MKT', '$88401.13');
INSERT INTO Car (make, model, price) VALUES ('Jeep', 'Grand Cherokee', '$13854.60');
INSERT INTO Car (make, model, price) VALUES ('Chrysler', 'Concorde', '$61496.12');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Aveo', '$96835.68');
INSERT INTO Car (make, model, price) VALUES ('Audi', 'R8', '$28253.43');
INSERT INTO Car (make, model, price) VALUES ('Porsche', '911', '$67627.67');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Grand Caravan', '$51202.52');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Uplander', '$73167.82');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Savana 3500', '$46441.20');
INSERT INTO Car (make, model, price) VALUES ('Lexus', 'SC', '$53551.99');
INSERT INTO Car (make, model, price) VALUES ('Honda', 'Element', '$66518.38');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Challenger', '$42701.57');
INSERT INTO Car (make, model, price) VALUES ('BMW', 'M5', '$47435.90');
INSERT INTO Car (make, model, price) VALUES ('Kia', 'Optima', '$79572.14');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Ram 2500', '$46156.27');
INSERT INTO Car (make, model, price) VALUES ('Jaguar', 'XJ Series', '$89425.37');
INSERT INTO Car (make, model, price) VALUES ('Lexus', 'LX', '$95015.97');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Corvette', '$24528.97');
INSERT INTO Car (make, model, price) VALUES ('Lincoln', 'Continental', '$39195.19');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Avalanche 2500', '$62128.16');
INSERT INTO Car (make, model, price) VALUES ('Porsche', 'Panamera', '$94813.19');
INSERT INTO Car (make, model, price) VALUES ('Oldsmobile', 'Intrigue', '$57889.25');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Golf', '$33615.59');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Ranger', '$97010.40');
INSERT INTO Car (make, model, price) VALUES ('Subaru', 'Legacy', '$29445.89');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Avalon', '$42576.31');
INSERT INTO Car (make, model, price) VALUES ('BMW', '550', '$97832.36');
INSERT INTO Car (make, model, price) VALUES ('Saturn', 'L-Series', '$30661.85');
INSERT INTO Car (make, model, price) VALUES ('Buick', 'Skylark', '$74130.90');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Envoy', '$80389.90');
INSERT INTO Car (make, model, price) VALUES ('BMW', '8 Series', '$51534.80');
INSERT INTO Car (make, model, price) VALUES ('Kia', 'Sportage', '$82887.71');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'MX-5', '$72264.78');
INSERT INTO Car (make, model, price) VALUES ('Suzuki', 'Grand Vitara', '$15693.27');
INSERT INTO Car (make, model, price) VALUES ('BMW', '3 Series', '$38180.78');
INSERT INTO Car (make, model, price) VALUES ('Subaru', 'Justy', '$42539.27');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'MPV', '$65293.28');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Challenger', '$44382.47');
INSERT INTO Car (make, model, price) VALUES ('Honda', 'Fit', '$19822.59');
INSERT INTO Car (make, model, price) VALUES ('Buick', 'Enclave', '$54769.85');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Suburban 2500', '$56176.24');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Suburban 1500', '$68734.55');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Aveo', '$61859.44');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'D150', '$14149.18');
INSERT INTO Car (make, model, price) VALUES ('Oldsmobile', 'LSS', '$62256.46');
INSERT INTO Car (make, model, price) VALUES ('Suzuki', 'Kizashi', '$87398.90');
INSERT INTO Car (make, model, price) VALUES ('Land Rover', 'LR4', '$52840.53');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'E-Class', '$51473.95');
INSERT INTO Car (make, model, price) VALUES ('Kia', 'Sportage', '$80864.63');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Lumina APV', '$63973.79');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Corvette', '$58071.18');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Sienna', '$31419.49');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', '3000GT', '$20863.57');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Trans Sport', '$93876.52');
INSERT INTO Car (make, model, price) VALUES ('Nissan', 'Sentra', '$68791.43');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Grand Am', '$26148.98');
INSERT INTO Car (make, model, price) VALUES ('Infiniti', 'FX', '$33588.25');
INSERT INTO Car (make, model, price) VALUES ('Saab', '9-3', '$21251.26');
INSERT INTO Car (make, model, price) VALUES ('Aston Martin', 'DBS', '$52877.11');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Eos', '$41110.15');
INSERT INTO Car (make, model, price) VALUES ('Subaru', 'Forester', '$25270.72');
INSERT INTO Car (make, model, price) VALUES ('Porsche', 'Boxster', '$41358.57');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Ram Van 3500', '$51402.93');
INSERT INTO Car (make, model, price) VALUES ('Land Rover', 'Discovery', '$16385.87');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Trans Sport', '$21064.54');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Transit Connect', '$76688.62');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Suburban 1500', '$41059.79');
INSERT INTO Car (make, model, price) VALUES ('Rolls-Royce', 'Phantom', '$31838.00');
INSERT INTO Car (make, model, price) VALUES ('Bentley', 'Brooklands', '$31983.54');
INSERT INTO Car (make, model, price) VALUES ('Honda', 'Civic Si', '$48716.67');
INSERT INTO Car (make, model, price) VALUES ('Mercury', 'Marauder', '$91566.64');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Chariot', '$22468.52');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Corsica', '$14440.61');
INSERT INTO Car (make, model, price) VALUES ('BMW', '7 Series', '$89194.15');
INSERT INTO Car (make, model, price) VALUES ('Lexus', 'GS', '$31085.94');
INSERT INTO Car (make, model, price) VALUES ('Acura', 'Integra', '$38676.91');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Dakota Club', '$92421.55');
INSERT INTO Car (make, model, price) VALUES ('Kia', 'Mentor', '$11566.22');
INSERT INTO Car (make, model, price) VALUES ('Nissan', 'Sentra', '$33235.22');
INSERT INTO Car (make, model, price) VALUES ('Bentley', 'Continental', '$59400.08');
INSERT INTO Car (make, model, price) VALUES ('Cadillac', 'STS', '$99310.67');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'MR2', '$47942.44');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Explorer', '$70443.30');
INSERT INTO Car (make, model, price) VALUES ('Land Rover', 'LR4', '$87815.82');
INSERT INTO Car (make, model, price) VALUES ('BMW', 'X5', '$48526.26');
INSERT INTO Car (make, model, price) VALUES ('Land Rover', 'Range Rover', '$83869.03');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Focus', '$27126.46');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Ram Wagon B250', '$21366.25');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Venture', '$85517.63');
INSERT INTO Car (make, model, price) VALUES ('Nissan', 'Leaf', '$85729.44');
INSERT INTO Car (make, model, price) VALUES ('Nissan', 'Maxima', '$83355.56');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Caprice Classic', '$21488.81');
INSERT INTO Car (make, model, price) VALUES ('Lincoln', 'Continental Mark VII', '$74408.68');
INSERT INTO Car (make, model, price) VALUES ('Lexus', 'RX Hybrid', '$38608.68');
INSERT INTO Car (make, model, price) VALUES ('Hyundai', 'Santa Fe', '$81618.72');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Paseo', '$38351.82');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Cabriolet', '$88743.20');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Jimmy', '$65089.49');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'E-Series', '$85464.71');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Land Cruiser', '$32259.00');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Ram', '$19534.74');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Edge', '$58005.21');
INSERT INTO Car (make, model, price) VALUES ('Suzuki', 'Swift', '$86984.46');
INSERT INTO Car (make, model, price) VALUES ('Acura', 'MDX', '$75094.33');
INSERT INTO Car (make, model, price) VALUES ('Mercury', 'Grand Marquis', '$26881.16');
INSERT INTO Car (make, model, price) VALUES ('Daewoo', 'Lanos', '$26684.44');
INSERT INTO Car (make, model, price) VALUES ('Volvo', 'S70', '$43439.01');
INSERT INTO Car (make, model, price) VALUES ('Hyundai', 'XG350', '$32097.64');
INSERT INTO Car (make, model, price) VALUES ('Audi', '100', '$64780.75');
INSERT INTO Car (make, model, price) VALUES ('Land Rover', 'Freelander', '$75654.55');
INSERT INTO Car (make, model, price) VALUES ('Lincoln', 'MKX', '$77655.98');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Sierra 1500', '$50145.97');
INSERT INTO Car (make, model, price) VALUES ('Oldsmobile', 'Achieva', '$39823.29');
INSERT INTO Car (make, model, price) VALUES ('Aptera', 'Typ-1', '$25887.32');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Tundra', '$16855.13');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'E-Series', '$46047.58');
INSERT INTO Car (make, model, price) VALUES ('Acura', 'ZDX', '$84807.61');
INSERT INTO Car (make, model, price) VALUES ('Mercury', 'Sable', '$16365.87');
INSERT INTO Car (make, model, price) VALUES ('Subaru', 'Tribeca', '$58884.21');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Jetta III', '$63900.52');
INSERT INTO Car (make, model, price) VALUES ('Buick', 'Rendezvous', '$95764.51');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'F150', '$36838.28');
INSERT INTO Car (make, model, price) VALUES ('Porsche', '928', '$96297.76');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'F350', '$76753.35');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'MX-6', '$82069.77');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Sierra 3500', '$85661.57');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'GLK-Class', '$93756.24');
INSERT INTO Car (make, model, price) VALUES ('Oldsmobile', 'Cutlass Supreme', '$16530.53');
INSERT INTO Car (make, model, price) VALUES ('Audi', 'RS 6', '$56424.49');
INSERT INTO Car (make, model, price) VALUES ('Lotus', 'Esprit', '$98831.21');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Sunbird', '$75721.55');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Grand Prix', '$97351.54');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Bonneville', '$39720.48');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Montana', '$64668.10');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'GTO', '$11595.20');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Eclipse', '$54535.57');
INSERT INTO Car (make, model, price) VALUES ('Infiniti', 'G35', '$39644.61');
INSERT INTO Car (make, model, price) VALUES ('Jeep', 'Patriot', '$83373.87');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Camry Hybrid', '$45221.91');
INSERT INTO Car (make, model, price) VALUES ('Mercury', 'Villager', '$60863.77');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Dakota', '$95054.65');
INSERT INTO Car (make, model, price) VALUES ('Acura', 'RL', '$73425.17');
INSERT INTO Car (make, model, price) VALUES ('Infiniti', 'QX56', '$46884.08');
INSERT INTO Car (make, model, price) VALUES ('Smart', 'Fortwo', '$60453.90');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Savana', '$88988.50');
INSERT INTO Car (make, model, price) VALUES ('Porsche', '924', '$94528.71');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Eurovan', '$50298.95');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'B-Series', '$47173.55');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Lancer', '$37875.13');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Jetta', '$49097.35');
INSERT INTO Car (make, model, price) VALUES ('Jaguar', 'X-Type', '$92371.79');
INSERT INTO Car (make, model, price) VALUES ('Suzuki', 'Reno', '$64359.32');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Suburban 2500', '$29189.21');
INSERT INTO Car (make, model, price) VALUES ('Audi', 'A6', '$83768.41');
INSERT INTO Car (make, model, price) VALUES ('Audi', '90', '$39716.20');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Cavalier', '$67932.72');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Firefly', '$19184.82');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Econoline E250', '$74859.72');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Grand Prix', '$32976.48');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'B-Series', '$62939.57');
INSERT INTO Car (make, model, price) VALUES ('Buick', 'Riviera', '$72222.00');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Eurovan', '$46608.62');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'SL-Class', '$80742.47');
INSERT INTO Car (make, model, price) VALUES ('Acura', 'RL', '$76975.29');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Firebird Trans Am', '$36553.23');
INSERT INTO Car (make, model, price) VALUES ('Volvo', '850', '$48219.16');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Savana 2500', '$79515.93');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Prizm', '$97817.58');
INSERT INTO Car (make, model, price) VALUES ('Porsche', 'Boxster', '$74039.02');
INSERT INTO Car (make, model, price) VALUES ('Kia', 'Sportage', '$15888.41');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'B-Series', '$65783.23');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'B-Series Plus', '$15326.42');
INSERT INTO Car (make, model, price) VALUES ('Saab', '9000', '$46161.38');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Grand Caravan', '$90404.57');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Tahoe', '$33957.18');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Magnum', '$32362.38');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'MX-5', '$42857.91');
INSERT INTO Car (make, model, price) VALUES ('Subaru', 'Tribeca', '$56899.51');
INSERT INTO Car (make, model, price) VALUES ('Hyundai', 'Elantra', '$31224.61');
INSERT INTO Car (make, model, price) VALUES ('Land Rover', 'Defender 90', '$13833.71');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Camry', '$76788.04');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Express 3500', '$52540.72');
INSERT INTO Car (make, model, price) VALUES ('Toyota', '4Runner', '$47606.53');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Challenger', '$71936.04');
INSERT INTO Car (make, model, price) VALUES ('Audi', 'Allroad', '$78676.70');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Challenger', '$69088.60');
INSERT INTO Car (make, model, price) VALUES ('Hyundai', 'Accent', '$67034.80');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Blazer', '$43716.52');
INSERT INTO Car (make, model, price) VALUES ('Kia', 'Sedona', '$23690.94');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'F250', '$74732.85');
INSERT INTO Car (make, model, price) VALUES ('Nissan', 'Altima', '$41592.34');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'GTO', '$11886.80');
INSERT INTO Car (make, model, price) VALUES ('Lexus', 'LS Hybrid', '$19085.11');
INSERT INTO Car (make, model, price) VALUES ('Saab', '900', '$74169.79');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Golf', '$97077.02');
INSERT INTO Car (make, model, price) VALUES ('Subaru', 'Outback', '$87694.19');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Savana', '$42188.75');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Camaro', '$63364.73');
INSERT INTO Car (make, model, price) VALUES ('Porsche', 'Cayenne', '$95292.33');
INSERT INTO Car (make, model, price) VALUES ('Audi', 'A4', '$81885.02');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Tacoma', '$80779.86');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Echo', '$13701.84');
INSERT INTO Car (make, model, price) VALUES ('Mercury', 'Grand Marquis', '$95732.97');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Scirocco', '$24801.95');
INSERT INTO Car (make, model, price) VALUES ('Jeep', 'Cherokee', '$36815.62');
INSERT INTO Car (make, model, price) VALUES ('Audi', 'Allroad', '$34092.56');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Pajero', '$77242.84');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Galant', '$32593.86');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Cabriolet', '$59888.14');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'SL-Class', '$82218.89');
INSERT INTO Car (make, model, price) VALUES ('Land Rover', 'Defender', '$71776.47');
INSERT INTO Car (make, model, price) VALUES ('Oldsmobile', 'Achieva', '$10494.67');
INSERT INTO Car (make, model, price) VALUES ('Nissan', 'GT-R', '$89028.02');
INSERT INTO Car (make, model, price) VALUES ('Maserati', 'Spyder', '$84989.94');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Ram Van B150', '$91908.09');
INSERT INTO Car (make, model, price) VALUES ('Hummer', 'H3', '$35894.38');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'T100 Xtra', '$37753.11');
INSERT INTO Car (make, model, price) VALUES ('Audi', 'A8', '$37290.83');
INSERT INTO Car (make, model, price) VALUES ('Maserati', 'Quattroporte', '$92800.70');
INSERT INTO Car (make, model, price) VALUES ('BMW', '6 Series', '$15414.53');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Expedition EL', '$11863.01');
INSERT INTO Car (make, model, price) VALUES ('Nissan', 'Sentra', '$19540.10');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Aveo', '$14738.53');
INSERT INTO Car (make, model, price) VALUES ('Mercury', 'Grand Marquis', '$28523.74');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'F-Series', '$83830.35');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Jimmy', '$21148.87');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Firebird', '$61306.12');
INSERT INTO Car (make, model, price) VALUES ('BMW', '5 Series', '$83378.95');
INSERT INTO Car (make, model, price) VALUES ('Mercury', 'Cougar', '$38509.52');
INSERT INTO Car (make, model, price) VALUES ('Hyundai', 'Entourage', '$74674.98');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Viper', '$54771.50');
INSERT INTO Car (make, model, price) VALUES ('BMW', 'Z3', '$75947.12');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Ram 1500', '$62530.13');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Bronco', '$91132.01');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'rio', '$60380.71');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Montero', '$76906.63');
INSERT INTO Car (make, model, price) VALUES ('BMW', 'M3', '$41765.01');
INSERT INTO Car (make, model, price) VALUES ('Mercury', 'Topaz', '$86870.82');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Windstar', '$60895.03');
INSERT INTO Car (make, model, price) VALUES ('Isuzu', 'i-370', '$72675.95');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Tundra', '$87220.85');
INSERT INTO Car (make, model, price) VALUES ('Nissan', 'Armada', '$11287.50');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Galant', '$66802.77');
INSERT INTO Car (make, model, price) VALUES ('Hyundai', 'Elantra', '$23350.61');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'F-Series', '$94716.01');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'RAV4', '$45464.12');
INSERT INTO Car (make, model, price) VALUES ('Volvo', '850', '$81321.79');
INSERT INTO Car (make, model, price) VALUES ('Porsche', 'Cayman', '$38670.98');
INSERT INTO Car (make, model, price) VALUES ('Chrysler', '300M', '$92137.25');
INSERT INTO Car (make, model, price) VALUES ('Jaguar', 'XJ', '$21569.29');
INSERT INTO Car (make, model, price) VALUES ('Honda', 'Ridgeline', '$68135.02');
INSERT INTO Car (make, model, price) VALUES ('Ferrari', 'F430', '$67891.48');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Tahoe', '$67908.24');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'E250', '$34628.95');
INSERT INTO Car (make, model, price) VALUES ('Jeep', 'Wrangler', '$91909.25');
INSERT INTO Car (make, model, price) VALUES ('Nissan', '240SX', '$10914.27');
INSERT INTO Car (make, model, price) VALUES ('Jeep', 'Wrangler', '$69555.60');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Tundra', '$62974.53');
INSERT INTO Car (make, model, price) VALUES ('Subaru', 'Legacy', '$76422.89');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Dakota Club', '$14608.33');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'Mazda3', '$33882.63');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Stratus', '$84154.72');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Jimmy', '$29529.25');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Montero', '$47580.58');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'GTI', '$36050.71');
INSERT INTO Car (make, model, price) VALUES ('Volvo', 'S60', '$39441.70');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'B-Series', '$74276.44');
INSERT INTO Car (make, model, price) VALUES ('Volvo', 'V40', '$74246.97');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Freestar', '$85680.29');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Monte Carlo', '$64247.31');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Sierra 2500', '$96480.39');
INSERT INTO Car (make, model, price) VALUES ('Nissan', 'Versa', '$61353.19');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Corvette', '$55598.72');
INSERT INTO Car (make, model, price) VALUES ('Honda', 'Civic', '$43140.66');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'F150', '$65472.00');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Truck', '$50166.02');
INSERT INTO Car (make, model, price) VALUES ('Hyundai', 'Veloster', '$93110.53');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Golf', '$49595.96');
INSERT INTO Car (make, model, price) VALUES ('Audi', 'S6', '$47866.26');
INSERT INTO Car (make, model, price) VALUES ('Saturn', 'VUE', '$29393.08');
INSERT INTO Car (make, model, price) VALUES ('Lexus', 'GS', '$62036.56');
INSERT INTO Car (make, model, price) VALUES ('Audi', 'Q7', '$51277.95');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Lumina', '$10515.75');
INSERT INTO Car (make, model, price) VALUES ('BMW', 'Z4 M', '$93655.34');
INSERT INTO Car (make, model, price) VALUES ('Acura', 'NSX', '$43102.49');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Silverado', '$84670.13');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Escort', '$60736.14');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'EXP', '$39550.90');
INSERT INTO Car (make, model, price) VALUES ('BMW', '7 Series', '$42342.58');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Corolla', '$16713.10');
INSERT INTO Car (make, model, price) VALUES ('Honda', 'Prelude', '$51003.29');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'G-Series G30', '$74766.53');
INSERT INTO Car (make, model, price) VALUES ('Lexus', 'GX', '$38066.90');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'GTO', '$73436.51');
INSERT INTO Car (make, model, price) VALUES ('Nissan', 'Sentra', '$53013.83');
INSERT INTO Car (make, model, price) VALUES ('Lotus', 'Esprit', '$83416.26');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Firefly', '$13961.41');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Durango', '$69408.77');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'CL-Class', '$72839.33');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'TundraMax', '$58102.33');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Cabriolet', '$13111.18');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Ram 2500', '$13008.41');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Durango', '$10225.65');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Blazer', '$26020.61');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Aveo', '$30672.02');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Aerostar', '$82737.61');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Caprice', '$15771.25');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Grand Prix', '$22346.95');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Express 1500', '$48994.88');
INSERT INTO Car (make, model, price) VALUES ('Volvo', 'C70', '$39362.77');
INSERT INTO Car (make, model, price) VALUES ('Eagle', 'Talon', '$18806.47');
INSERT INTO Car (make, model, price) VALUES ('Nissan', 'Altima', '$79033.74');
INSERT INTO Car (make, model, price) VALUES ('Subaru', 'SVX', '$70502.14');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Tempo', '$66673.46');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Ram 50', '$59332.92');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Touareg', '$20845.67');
INSERT INTO Car (make, model, price) VALUES ('Bentley', 'Continental GTC', '$36220.99');
INSERT INTO Car (make, model, price) VALUES ('Honda', 'Odyssey', '$66329.45');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Cordia', '$79276.18');
INSERT INTO Car (make, model, price) VALUES ('Subaru', 'Forester', '$36153.60');
INSERT INTO Car (make, model, price) VALUES ('Spyker', 'C8 Spyder Wide Body', '$12513.37');
INSERT INTO Car (make, model, price) VALUES ('BMW', 'X6 M', '$48846.06');
INSERT INTO Car (make, model, price) VALUES ('Buick', 'LaCrosse', '$95492.46');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Ram 2500', '$26923.06');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Metro', '$26796.84');
INSERT INTO Car (make, model, price) VALUES ('Hummer', 'H2 SUV', '$64496.55');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Suburban 2500', '$10346.52');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'Mazda5', '$84844.67');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Camaro', '$59637.67');
INSERT INTO Car (make, model, price) VALUES ('Lexus', 'LS', '$24961.92');
INSERT INTO Car (make, model, price) VALUES ('Kia', 'Rio', '$71358.37');
INSERT INTO Car (make, model, price) VALUES ('Chrysler', 'Town & Country', '$31462.59');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'G55 AMG', '$67122.44');
INSERT INTO Car (make, model, price) VALUES ('Oldsmobile', 'Achieva', '$85061.28');
INSERT INTO Car (make, model, price) VALUES ('Chrysler', 'Sebring', '$50515.18');
INSERT INTO Car (make, model, price) VALUES ('BMW', '530', '$51024.34');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Golf', '$72249.70');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Grand Prix', '$29300.86');
INSERT INTO Car (make, model, price) VALUES ('Lexus', 'ES', '$51070.25');
INSERT INTO Car (make, model, price) VALUES ('Cadillac', 'Eldorado', '$78808.17');
INSERT INTO Car (make, model, price) VALUES ('Oldsmobile', 'Alero', '$19996.35');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Ranger', '$38292.79');
INSERT INTO Car (make, model, price) VALUES ('Oldsmobile', 'Alero', '$51366.64');
INSERT INTO Car (make, model, price) VALUES ('Maybach', '62', '$98594.39');
INSERT INTO Car (make, model, price) VALUES ('Eagle', 'Summit', '$19295.42');
INSERT INTO Car (make, model, price) VALUES ('Buick', 'Somerset', '$86038.11');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Silverado 2500', '$74775.08');
INSERT INTO Car (make, model, price) VALUES ('Jaguar', 'XJ Series', '$81443.20');
INSERT INTO Car (make, model, price) VALUES ('Lotus', 'Esprit', '$59946.75');
INSERT INTO Car (make, model, price) VALUES ('Hyundai', 'Accent', '$71233.39');
INSERT INTO Car (make, model, price) VALUES ('Infiniti', 'I', '$48469.05');
INSERT INTO Car (make, model, price) VALUES ('Scion', 'tC', '$93717.69');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Astro', '$42449.55');
INSERT INTO Car (make, model, price) VALUES ('Chrysler', 'Town & Country', '$96865.97');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'F350', '$73923.76');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Suburban 1500', '$11163.15');
INSERT INTO Car (make, model, price) VALUES ('Oldsmobile', '98', '$82481.09');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Econoline E150', '$21116.15');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'MX-5', '$74219.04');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Grand Prix', '$37624.57');
INSERT INTO Car (make, model, price) VALUES ('Suzuki', 'Samurai', '$74574.24');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'Millenia', '$57958.80');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'CX-9', '$58723.61');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'MX-6', '$86453.96');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Lancer', '$34773.55');
INSERT INTO Car (make, model, price) VALUES ('Hyundai', 'Elantra', '$34834.54');
INSERT INTO Car (make, model, price) VALUES ('Nissan', 'Murano', '$54994.47');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Galant', '$79330.99');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Camry', '$17644.03');
INSERT INTO Car (make, model, price) VALUES ('Maserati', 'Quattroporte', '$75228.57');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Sunfire', '$34600.75');
INSERT INTO Car (make, model, price) VALUES ('Lincoln', 'Mark VIII', '$54070.41');
INSERT INTO Car (make, model, price) VALUES ('Honda', 'Insight', '$46091.03');
INSERT INTO Car (make, model, price) VALUES ('Bugatti', 'Veyron', '$39485.31');
INSERT INTO Car (make, model, price) VALUES ('Maybach', '57', '$89578.83');
INSERT INTO Car (make, model, price) VALUES ('Lotus', 'Esprit', '$31241.30');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Durango', '$34038.27');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Ram 2500', '$38930.08');
INSERT INTO Car (make, model, price) VALUES ('Infiniti', 'J', '$19218.53');
INSERT INTO Car (make, model, price) VALUES ('Volvo', 'XC70', '$35652.94');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Sunbird', '$90124.25');
INSERT INTO Car (make, model, price) VALUES ('Honda', 'Accord Crosstour', '$55617.99');
INSERT INTO Car (make, model, price) VALUES ('BMW', 'Z4', '$90984.42');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Paseo', '$39680.85');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'C-Class', '$32631.85');
INSERT INTO Car (make, model, price) VALUES ('Hyundai', 'Sonata', '$93070.00');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'S-Class', '$72760.13');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Eurovan', '$99812.08');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Laser', '$46810.56');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Vandura 3500', '$59039.00');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Impala', '$76000.60');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Suburban 1500', '$30076.79');
INSERT INTO Car (make, model, price) VALUES ('Cadillac', 'STS-V', '$51572.51');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Grand Prix', '$12939.91');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Acadia', '$79277.73');
INSERT INTO Car (make, model, price) VALUES ('Honda', 'Accord', '$75843.24');
INSERT INTO Car (make, model, price) VALUES ('Jeep', 'Liberty', '$91514.88');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'S10', '$14377.09');
INSERT INTO Car (make, model, price) VALUES ('Nissan', 'GT-R', '$38382.80');
INSERT INTO Car (make, model, price) VALUES ('Lincoln', 'Continental', '$32431.17');
INSERT INTO Car (make, model, price) VALUES ('BMW', 'M6', '$44395.41');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Envoy', '$17699.14');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'HHR', '$40321.13');
INSERT INTO Car (make, model, price) VALUES ('Buick', 'Century', '$52928.72');
INSERT INTO Car (make, model, price) VALUES ('Honda', 'CR-V', '$86981.77');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Touareg 2', '$52684.09');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Corvette', '$80224.87');
INSERT INTO Car (make, model, price) VALUES ('Chrysler', 'Concorde', '$33962.96');
INSERT INTO Car (make, model, price) VALUES ('Lexus', 'LX', '$15355.29');
INSERT INTO Car (make, model, price) VALUES ('Subaru', 'Outback', '$71612.54');
INSERT INTO Car (make, model, price) VALUES ('Audi', 'TT', '$92780.87');
INSERT INTO Car (make, model, price) VALUES ('Saab', '9-5', '$63783.81');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Expo', '$88743.37');
INSERT INTO Car (make, model, price) VALUES ('Acura', 'TL', '$15233.74');
INSERT INTO Car (make, model, price) VALUES ('Hyundai', 'Santa Fe', '$57030.60');
INSERT INTO Car (make, model, price) VALUES ('Mercury', 'Tracer', '$18997.90');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Corsica', '$31736.15');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'MX-5', '$62867.97');
INSERT INTO Car (make, model, price) VALUES ('Saturn', 'VUE', '$83569.17');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Suburban', '$46713.30');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Raider', '$11150.99');
INSERT INTO Car (make, model, price) VALUES ('Lotus', 'Esprit', '$72444.24');
INSERT INTO Car (make, model, price) VALUES ('Hyundai', 'Sonata', '$82825.56');
INSERT INTO Car (make, model, price) VALUES ('Land Rover', 'Discovery', '$67374.27');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'F450', '$75668.99');
INSERT INTO Car (make, model, price) VALUES ('Buick', 'Somerset', '$95137.47');
INSERT INTO Car (make, model, price) VALUES ('Isuzu', 'Trooper', '$69384.09');
INSERT INTO Car (make, model, price) VALUES ('Kia', 'Sorento', '$64705.95');
INSERT INTO Car (make, model, price) VALUES ('Austin', 'Mini', '$57098.47');
INSERT INTO Car (make, model, price) VALUES ('Jaguar', 'XJ Series', '$33862.10');
INSERT INTO Car (make, model, price) VALUES ('Suzuki', 'SJ', '$90964.52');
INSERT INTO Car (make, model, price) VALUES ('Land Rover', 'Range Rover Sport', '$89768.51');
INSERT INTO Car (make, model, price) VALUES ('Suzuki', 'Swift', '$75075.61');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'New Beetle', '$74316.11');
INSERT INTO Car (make, model, price) VALUES ('Chrysler', '300M', '$26245.15');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Silverado', '$51698.63');
INSERT INTO Car (make, model, price) VALUES ('Nissan', 'Maxima', '$24872.46');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Festiva', '$68801.23');
INSERT INTO Car (make, model, price) VALUES ('Lexus', 'LX', '$64010.48');
INSERT INTO Car (make, model, price) VALUES ('Suzuki', 'Swift', '$78754.81');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Challenger', '$43666.01');
INSERT INTO Car (make, model, price) VALUES ('Suzuki', 'SX4', '$23583.97');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Avalon', '$70720.21');
INSERT INTO Car (make, model, price) VALUES ('Lincoln', 'Town Car', '$73330.77');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'LeMans', '$36253.96');
INSERT INTO Car (make, model, price) VALUES ('Honda', 'Civic', '$53564.76');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Raider', '$68766.54');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Sunfire', '$44548.23');
INSERT INTO Car (make, model, price) VALUES ('Plymouth', 'Sundance', '$97945.82');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Suburban 1500', '$55039.43');
INSERT INTO Car (make, model, price) VALUES ('Lexus', 'LS', '$80499.83');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'F150', '$25189.98');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Tacoma', '$18953.96');
INSERT INTO Car (make, model, price) VALUES ('Suzuki', 'Grand Vitara', '$45689.66');
INSERT INTO Car (make, model, price) VALUES ('Infiniti', 'G35', '$85633.51');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Tacoma Xtra', '$79885.40');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'Miata MX-5', '$39193.71');
INSERT INTO Car (make, model, price) VALUES ('Chrysler', 'Cirrus', '$66520.90');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'CLS-Class', '$96561.36');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'CLS-Class', '$37830.71');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Camaro', '$14200.87');
INSERT INTO Car (make, model, price) VALUES ('GMC', 'Sonoma Club', '$70269.39');
INSERT INTO Car (make, model, price) VALUES ('Oldsmobile', 'Cutlass', '$11508.89');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Tundra', '$28972.20');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Sunbird', '$67363.16');
INSERT INTO Car (make, model, price) VALUES ('Land Rover', 'Freelander', '$59598.57');
INSERT INTO Car (make, model, price) VALUES ('Audi', 'S4', '$16325.94');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Escape', '$93956.92');
INSERT INTO Car (make, model, price) VALUES ('Plymouth', 'Laser', '$68657.93');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Galant', '$21559.55');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Focus', '$67939.49');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Stratus', '$34491.42');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Caravan', '$85708.69');
INSERT INTO Car (make, model, price) VALUES ('Porsche', 'Cayenne', '$11091.20');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Econoline E350', '$99637.82');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Focus', '$13594.35');
INSERT INTO Car (make, model, price) VALUES ('Acura', 'TL', '$74456.33');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Express 1500', '$91340.96');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'F150', '$59655.33');
INSERT INTO Car (make, model, price) VALUES ('Lincoln', 'Continental', '$64627.33');
INSERT INTO Car (make, model, price) VALUES ('Volvo', '850', '$76675.50');
INSERT INTO Car (make, model, price) VALUES ('Audi', 'Coupe GT', '$59852.04');
INSERT INTO Car (make, model, price) VALUES ('BMW', '8 Series', '$66827.23');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Mirage', '$53967.21');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Viper', '$78268.44');
INSERT INTO Car (make, model, price) VALUES ('BMW', '3 Series', '$33531.82');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Dakota', '$72646.27');
INSERT INTO Car (make, model, price) VALUES ('Chrysler', 'Town & Country', '$97694.41');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Prius', '$56459.58');
INSERT INTO Car (make, model, price) VALUES ('Nissan', 'Murano', '$92582.56');
INSERT INTO Car (make, model, price) VALUES ('Mercury', 'Topaz', '$11921.53');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Tahoe', '$89281.64');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Stratus', '$31134.73');
INSERT INTO Car (make, model, price) VALUES ('Suzuki', 'Esteem', '$41814.17');
INSERT INTO Car (make, model, price) VALUES ('Land Rover', 'Range Rover', '$90786.30');
INSERT INTO Car (make, model, price) VALUES ('Hyundai', 'Accent', '$23016.94');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Monte Carlo', '$26233.00');
INSERT INTO Car (make, model, price) VALUES ('Mercedes-Benz', 'W201', '$44874.11');
INSERT INTO Car (make, model, price) VALUES ('Buick', 'Enclave', '$91026.27');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'Contour', '$13192.42');
INSERT INTO Car (make, model, price) VALUES ('Subaru', 'Leone', '$25183.68');
INSERT INTO Car (make, model, price) VALUES ('Porsche', 'Boxster', '$27472.32');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Montero', '$77096.26');
INSERT INTO Car (make, model, price) VALUES ('Mitsubishi', 'Tredia', '$77523.27');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'E-Series', '$50803.50');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Corvette', '$76637.79');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'GTI', '$47373.88');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'MPV', '$30252.37');
INSERT INTO Car (make, model, price) VALUES ('Volvo', '850', '$98324.01');
INSERT INTO Car (make, model, price) VALUES ('Mercury', 'Sable', '$22323.12');
INSERT INTO Car (make, model, price) VALUES ('Isuzu', 'Rodeo', '$25194.19');
INSERT INTO Car (make, model, price) VALUES ('Mazda', 'MX-6', '$75988.02');
INSERT INTO Car (make, model, price) VALUES ('Toyota', 'Highlander', '$39457.87');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Monaco', '$26935.67');
INSERT INTO Car (make, model, price) VALUES ('Plymouth', 'Voyager', '$54810.02');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Blazer', '$74289.27');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'E350', '$34453.23');
INSERT INTO Car (make, model, price) VALUES ('Eagle', 'Vision', '$78506.01');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Grand Caravan', '$44926.28');
INSERT INTO Car (make, model, price) VALUES ('BMW', 'Z8', '$75963.08');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'TrailBlazer', '$88891.19');
INSERT INTO Car (make, model, price) VALUES ('Audi', 'S8', '$28651.79');
INSERT INTO Car (make, model, price) VALUES ('Isuzu', 'Rodeo', '$72771.43');
INSERT INTO Car (make, model, price) VALUES ('Pontiac', 'Firebird', '$57199.86');
INSERT INTO Car (make, model, price) VALUES ('Mercury', 'Topaz', '$14991.78');
INSERT INTO Car (make, model, price) VALUES ('Bentley', 'Continental', '$85500.54');
INSERT INTO Car (make, model, price) VALUES ('Jaguar', 'X-Type', '$94358.02');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Caravan', '$70074.78');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'Golf', '$80801.73');
INSERT INTO Car (make, model, price) VALUES ('Chrysler', 'Concorde', '$68437.08');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'Dakota Club', '$50473.10');
INSERT INTO Car (make, model, price) VALUES ('Chevrolet', 'Camaro', '$70867.56');
INSERT INTO Car (make, model, price) VALUES ('BMW', 'M3', '$73177.29');
INSERT INTO Car (make, model, price) VALUES ('MINI', 'Cooper', '$57313.51');
INSERT INTO Car (make, model, price) VALUES ('Ford', 'E350', '$51278.63');
INSERT INTO Car (make, model, price) VALUES ('Volkswagen', 'GTI', '$20243.15');
INSERT INTO Car (make, model, price) VALUES ('Dodge', 'D250', '$53354.22');
